card_deck_translation = {
    "Eight of Hearts": '8h',
    "Three of Diamonds": '3d',
    "Three of Clubs": '3c',
    "Nine of Spades": '9s',
    "Four of Diamonds": '4d',
    "Six of Diamonds": '6d',
    "Queen of Clubs": 'qc',
    "Eight of Diamonds": '8d',
    "King of Spades": 'ks',
    "Three of Hearts": '3h',
    "Jack of Diamonds": 'jd',
    "Five of Hearts": '5h',
    "Six of Clubs": '6c',
    "Nine of Hearts": '9h',
    "Four of Clubs": '4c',
    "Jack of Clubs": 'jc',
    "Five of Diamonds": '5d',
    "Seven of Clubs": '7c',
    "King of Hearts": 'kh',
    "Ten of Spades": '10s',
    "Two of Spades": '2s',
    "Nine of Clubs": '9c',
    "Two of Diamonds": '2d',
    "Three of Spades": '3s',
    "Eight of Spades": '8s',
    "Two of Hearts": '2h',
    "Two of Clubs": '2c',
    "Ace of Hearts": 'ah',
    "Queen of Diamonds": 'qd',
    "Jack of Hearts": 'jh',
    "Ten of Hearts": '10h',
    "Seven of Diamonds": '7d',
    "Jack of Spades": 'js',
    "Queen of Spades": 'qs',
    "Four of Hearts": '4h',
    "Six of Hearts": '6h',
    "Seven of Hearts": '7h',
    "Four of Spades": '4s',
    "Ten of Clubs": '10c',
    "Six of Spades": '6s',
    "Eight of Clubs": '8c',
    "Ten of Diamonds": '10d',
    "Five of Clubs": '5c',
    "Ace of Clubs": 'ac',
    "King of Clubs": 'kc',
    "King of Diamonds": 'kd',
    "Nine of Diamonds": '9d',
    "Ace of Spades": 'as',
    "Five of Spades": '5s',
    "Seven of Spades": '7s',
    "Ace of Diamonds": 'ad',
    "Queen of Hearts": 'qh'
}

deck = {
    '2h': 2, '3h': 3, '4h': 4, '5h': 5, '6h': 6, '7h': 7, '8h': 8, '9h': 9, '10h': 10, 'jh': 10, 'qh': 10, 'kh': 10, 'ah': 11,
    '2d': 2, '3d': 3, '4d': 4, '5d': 5, '6d': 6, '7d': 7, '8d': 8, '9d': 9, '10d': 10, 'jd': 10, 'qd': 10, 'kd': 10, 'ad': 11,
    '2c': 2, '3c': 3, '4c': 4, '5c': 5, '6c': 6, '7c': 7, '8c': 8, '9c': 9, '10c': 10, 'jc': 10, 'qc': 10, 'kc': 10, 'ac': 11,
    '2s': 2, '3s': 3, '4s': 4, '5s': 5, '6s': 6, '7s': 7, '8s': 8, '9s': 9, '10s': 10, 'js': 10, 'qs': 10, 'ks': 10, 'as': 11,
}

wordToMap = {
    "Two of Hearts": '2h',
    "Three of Hearts": '3h',
    "Four of Hearts": '4h',
    "Five of Hearts": '5h',
    "Six of Hearts": '6h',
    "Seven of Hearts": '7h',
    "Eight of Hearts": '8h',
    "Nine of Hearts": '9h',
    "Ten of Hearts": '10h',
    "Jack of Hearts": 'jh',
    "Queen of Hearts": 'qh',
    "King of Hearts": 'kh',
    "Ace of Hearts": 'ah',
    "Two of Diamonds": '2d',
    "Three of Diamonds": '3d',
    "Four of Diamonds": '4d',
    "Five of Diamonds": '5d',
    "Six of Diamonds": '6d',
    "Seven of Diamonds": '7d',
    "Eight of Diamonds": '8d',
    "Nine of Diamonds": '9d',
    "Ten of Diamonds": '10d',
    "Jack of Diamonds": 'jd',
    "Queen of Diamonds": 'qd',
    "King of Diamonds": 'kd',
    "Ace of Diamonds": 'ad',
    "Two of Clubs": '2c',
    "Three of Clubs": '3c',
    "Four of Clubs": '4c',
    "Five of Clubs": '5c',
    "Six of Clubs": '6c',
    "Seven of Clubs": '7c',
    "Eight of Clubs": '8c',
    "Nine of Clubs": '9c',
    "Ten of Clubs": '10c',
    "Jack of Clubs": 'jc',
    "Queen of Clubs": 'qc',
    "King of Clubs": 'kc',
    "Ace of Clubs": 'ac',
    "Two of Spades": '2s',
    "Three of Spades": '3s',
    "Four of Spades": '4s',
    "Five of Spades": '5s',
    "Six of Spades": '6s',
    "Seven of Spades": '7s',
    "Eight of Spades": '8s',
    "Nine of Spades": '9s',
    "Ten of Spades": '10s',
    "Jack of Spades": 'js',
    "Queen of Spades": 'qs',
    "King of Spades": 'ks',
    "Ace of Spades": 'as',
}

card_map = {
    0: 'Ace of Clubs', 1: 'Ace of Diamonds', 2: 'Ace of Hearts', 3: 'Ace of Spades',
    4: 'Eight of Clubs', 5: 'Eight of Diamonds', 6: 'Eight of Hearts', 7: 'Eight of Spades',
    8: 'Five of Clubs', 9: 'Five of Diamonds', 10: 'Five of Hearts', 11: 'Five of Spades',
    12: 'Four of Clubs', 13: 'Four of Diamonds', 14: 'Four of Hearts', 15: 'Four of Spades',
    16: 'Jack of Clubs', 17: 'Jack of Diamonds', 18: 'Jack of Hearts', 19: 'Jack of Spades',
    20: 'Joker', 21: 'King of Clubs', 22: 'King of Diamonds', 23: 'King of Hearts', 24: 'King of Spades',
    25: 'Nine of Clubs', 26: 'Nine of Diamonds', 27: 'Nine of Hearts', 28: 'Nine of Spades',
    29: 'Queen of Clubs', 30: 'Queen of Diamonds', 31: 'Queen of Hearts', 32: 'Queen of Spades',
    33: 'Seven of Clubs', 34: 'Seven of Diamonds', 35: 'Seven of Hearts', 36: 'Seven of Spades',
    37: 'Six of Clubs', 38: 'Six of Diamonds', 39: 'Six of Hearts', 40: 'Six of Spades',
    41: 'Ten of Clubs', 42: 'Ten of Diamonds', 43: 'Ten of Hearts', 44: 'Ten of Spades',
    45: 'Three of Clubs', 46: 'Three of Diamonds', 47: 'Three of Hearts', 48: 'Three of Spades',
    49: 'Two of Clubs', 50: 'Two of Diamonds', 51: 'Two of Hearts', 52: 'Two of Spades'
}

# card_map = {0: 'ace of clubs', 1: 'ace of diamonds', 2: 'ace of hearts', 3: 'ace of spades', 4: 'eight of clubs', 5: 'eight of diamonds', 6: 'eight of hearts', 7: 'eight of spades', 8: 'five of clubs', 9: 'five of diamonds', 10: 'five of hearts', 11: 'five of spades', 12: 'four of clubs', 13: 'four of diamonds', 14: 'four of hearts', 15: 'four of spades', 16: 'jack of clubs', 17: 'jack of diamonds', 18: 'jack of hearts', 19: 'jack of spades', 20: 'joker', 21: 'king of clubs', 22: 'king of diamonds', 23: 'king of hearts', 24: 'king of spades', 25: 'nine of clubs', 26: 'nine of diamonds', 27: 'nine of hearts', 28: 'nine of spades', 29: 'queen of clubs', 30: 'queen of diamonds', 31: 'queen of hearts', 32: 'queen of spades', 33: 'seven of clubs', 34: 'seven of diamonds', 35: 'seven of hearts', 36: 'seven of spades', 37: 'six of clubs', 38: 'six of diamonds', 39: 'six of hearts', 40: 'six of spades', 41: 'ten of clubs', 42: 'ten of diamonds', 43: 'ten of hearts', 44: 'ten of spades', 45: 'three of clubs', 46: 'three of diamonds', 47: 'three of hearts', 48: 'three of spades', 49: 'two of clubs', 50: 'two of diamonds', 51: 'two of hearts', 52: 'two of spades'}